webapp/market/models.py
from flask_sqlalchemy import SQLAlchemy
from webapp import config

from webapp.db import db


class Vitamins(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String, nullable=False)
    price = db.Column(db.Integer, nullable=False)
    image = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    
    @property
    def image_path(self):
        return f'/{config.MEDIA_DIR}/{self.image}'

    def __repr__(self):
        return self.name

webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from webapp.db import db

favorite = db.Table(
    'favorite',
    db.Column('product_id', db.Integer, db.ForeignKey('vitamins.id'), primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('user.id'), primary_key=True)
)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(50))
    favorite = db.relationship(
        'Vitamins',
        secondary=favorite,
        lazy='subquery',
        backref=db.backref('users', lazy=True)
    )

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return '<User {}>'.format(self.username)

    @property
    def is_user(self):
        return self.role == 'user'

webapp/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    username = StringField('Имя пользователя',validators=[DataRequired()],
          render_kw={"class": "form-control"})
    password = PasswordField('Пароль',validators=[DataRequired()],
          render_kw={"class": "form-control"})
    remember_me = BooleanField('Запомнить меня', default=True,
            render_kw={"class": "form-check-input"})
    submit = SubmitField('Отправить',render_kw={"class":"btn btn-primary"})



    def __repr__(self):
        return '<User {}>'.format(self.username)

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from webapp.user.models import User


class LoginForm(FlaskForm):
    username = StringField(
        'Имя пользователя',
        validators=[DataRequired()],
        render_kw={"class": "form-control"},
    )
    password = PasswordField(
        'Пароль',
        validators=[DataRequired()],
        render_kw={"class": "form-control"},
    )
    remember_me = BooleanField(
        'Запомнить меня',
        default=True,
        render_kw={"class": "form-check-input"},
    )
    submit = SubmitField(
        'Отправить',
        render_kw={"class": "btn btn-primary"},
    )


class RegistrationForm(FlaskForm):
    username = StringField(
        'Имя пользователя',
        validators=[DataRequired()],
        render_kw={"class": "form-control"},
    )
    email = StringField(
        'Электронная почта',
        validators=[DataRequired(), Email()],
        render_kw={"class": "form-control"},
    )
    password = PasswordField(
        'Пароль',
        validators=[DataRequired()],
        render_kw={"class": "form-control"},
    )
    password2 = PasswordField(
        'Повторите пароль',
        validators=[DataRequired(), EqualTo('password')],
        render_kw={"class": "form-control"},
    )
    submit = SubmitField(
        'Отправить',
        render_kw={"class": "btn btn-primary"},
    )

    def validate_username(self, username):
        users_count = User.query.filter_by(username=username.data).count()
        if users_count > 0:
            raise ValidationError('Пользователь с таким именем уже зарегистрирован')

    def validate_email(self, email):
        users_count = User.query.filter_by(email=email.data).count()
        if users_count > 0:
            raise ValidationError(
                'Пользователь с такой электронной почтой уже зарегистрирован')

webapp/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate

from webapp.db import db
from webapp.market.views import blueprint as market_blueprint
# from webapp.market.models import Vitamins
from webapp.user.models import User
from webapp.user.views import blueprint as user_blueprint
from . import commands


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)
    migrate = Migrate(app, db)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'

    app.register_blueprint(market_blueprint)
    app.register_blueprint(user_blueprint)

    register_commands(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    return app


def register_commands(app):
    app.cli.add_command(commands.save_products)
    

webapp/market/views.py
from flask import Blueprint, render_template, request
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import func

from webapp.market.models import Vitamins
from webapp import db
#db = SQLAlchemy()

blueprint = Blueprint('market', __name__)


@blueprint.route("/")
def index():
    page_title = 'Витамины и БАДы NOW'
    title = 'Введите название и дозировку:'
    name = request.args.get('name', None)
    
    query = db.select(Vitamins)
    if name:
        query = query.filter(func.lower(Vitamins.name).contains(name.lower()))
    vitamins = db.session.execute(query.order_by(Vitamins.price)).scalars()
    
    return render_template('market/index.html', page_title=page_title, title=title, vitamins=vitamins)

webapp/user/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user

from webapp.db import db
from webapp.user.decorators import user_required
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.market.models import Vitamins

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('market.index'))

    title = "Авторизация"
    login_form = LoginForm()
    return render_template('user/login.html', title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы успешно авторизовались')
            return redirect(url_for('market.index'))

    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    flash('Вы вышли изучетной записи')
    logout_user()
    return redirect(url_for('market.index'))


@blueprint.route('/user')
@user_required
def user_index():
    page_title = 'Витамины и БАДы NOW. Избранное.'
    if current_user.is_user:
        return render_template('user/user.html', page_title=page_title, current_user=current_user)


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('market.index'))
    form = RegistrationForm()
    title = "Регистрация"
    return render_template('user/registration.html', title=title, form=form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(getattr(form, field).label.text, error))
        return redirect(url_for('user.register'))

@blueprint.route('/like/<int:product_id>')
def like(product_id):
    product = db.get_or_404(Vitamins, product_id)
    current_user.favorite.append(product)
    db.session.add(current_user)
    db.session.commit()
    flash(f'{product.name} добавлено в избранное')
    return redirect(url_for('market.index', **request.args))


    

webapp/templates/base.html
<!doctype html>
    <html lang="ru">
      <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
        <title>{{page_title}}</title>
      </head>
      <body>
        {% include 'menu.html' %}
        <div class = "container">
        <p class = "text-end">
            <h3>{{title}}</h3>
        </p>
        {% block content %}{% endblock %}
        </div>
        <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        </body>
        </html>

webapp/templates/market/index.html
{% extends "base.html" %}

{%block content%}
  <div class = "row">
      <div class = 'col-12' >
        {% with messages = get_flashed_messages() %}
          {% if messages %}
          <div class="alert alert-warning" role="alert">
              {% for message in messages %}
                  {{ message }}<br>
              {% endfor %}
          </div>
          {% endif %}
        {% endwith %} 
          <form class="d-flex" role="search">
              <input name="name" input class="form-control me-1" type="search" placeholder="Например: D3 5000" aria-label="Search">
              <button class="btn btn-primary" type="submit">Поиск</button> 
          </form>
          <div class="col">
            {% if request.args.get('name') %}
              <h5>Результаты поиска по запросу: {{ request.args.get('name') }}</h5>
            {% endif %}
          
            {% if request.args.get('name') %}
            <div class="row">
              {% for vitamin in vitamins %}
                <div class="col-3 mt-3">
                  <div class="card" style="width: 18rem;">
                    <img src="{{ vitamin.image }}" class="card-img-top" alt="{{vitamin.name}}" style="height: 300px;">
                    <div class="card-body">
                      <h5 class="card-title"> Цена: {{ vitamin.price }} ₽</h5>
                      <p class="text-truncate">{{ vitamin.name }}</p>
                      <a href= "{{ vitamin.url }}" class="btn btn-primary">Купить</a>
                      <a href="{{ url_for('user.like', product_id=vitamin.id, **dict(request.args)) }}"  class="btn btn-outline-info">В избранное💙</a>
                    </div>
                  </div>
                </div>
               {%endfor%}
            </div>
            {% endif %}
            </div>
          </div>
      </div>
  </div>
{%endblock%}

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Поиск и сравнение 🔍</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('user.user_index') }}">Избранное 💙</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">-------------------------------------></a>
          </li>


          <a class='btn btn-primary' href='https://www.nowfoods.com/'><img src='https://g-academy.ru/sites/default/files/2021-11/Muse%20%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0%20%28%20%D1%81%20%D0%B1%D0%B5%D0%BB%D1%8B%D0%BC%20%D1%84%D0%BE%D0%BD%D0%BE%D0%BC%20%29.png' class="img-fluid" width="100" height="50"></a>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"> <-------------------------------------</a>
          </li>

          <li class="nav-item dropdown">
            <a id="drop1" href="users" role="button" class="dropdown-toggle" data-toggle="dropdown">Личный кабинет 👤
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{{ url_for('user.register') }}">Регистрация нового пользователя 🆔</a></li>
              <li><a class="dropdown-item" href="{{ url_for('user.login') }}">Авторизация ✅</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{{ url_for('user.logout') }}">Выход 📴</a></li>
            </ul>
          </li>
        </ul>
        
      </div>
    </div>
  </nav>
 

webapp/templates/user/login.html
{% extends "base.html" %}

{%block content%}

      <div class = 'row'>
          <div class = 'col-4'>
              {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
              {% endwith %}
              <form action="{{url_for('user.process_login')}}" method="post">
                  {{ form.hidden_tag() }}
                  <div class="form-group">
                      {{ form.username.label }}
                      {{ form.username() }}
                  </div>
                  <div class="form-group">
                      {{ form.password.label }}
                      {{ form.password() }}
                  </div>
                  <div class="form-group form-check">
                    {{ form.remember_me() }}
                    {{ form.remember_me.label(class_='form-check-label') }}
                  </div>
                  {{ form.submit }}
              </form>
          </div>
          <div class = 'col-8'>
      </div>
  </div>
{%endblock%}

webapp/templates/user/registration.html
{% extends "base.html" %}

{%block content%}

      <div class = 'row'>
          <div class = 'col-4'>
              {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
              {% endwith %}
              <form action="{{url_for('user.process_reg')}}" method="post">
                  {{ form.hidden_tag() }}
                  <div class="form-group">
                      {{ form.username.label }}
                      {{ form.username() }}
                  </div>
                  <div class="form-group">
                    {{ form.email.label }}
                    {{ form.email() }}
                  </div>
                  <div class="form-group">
                      {{ form.password.label }}
                      {{ form.password() }}
                  </div>
                  <div class="form-group">
                    {{ form.password2.label }}
                    {{ form.password2() }}
                  </div>
                  {{ form.submit }}
              </form>
          </div>
          <div class = 'col-8'>
      </div>
  </div>
{%endblock%}

webapp/templates/user/user.html
{% extends "base.html" %}

{%block content%}
  <div class = "container">
  <h3>Избранное 💙</h3>
  <div class="row">
  {% for favorite in current_user.favorite %}
  <div class="col-3 mt-3">
    <div class="card" style="width: 18rem;">
      <img src="{{ favorite.image}}" class="card-img-top" alt="{{favorite.name}}" style="height: 300px;">
      <div class="card-body">
        <h5 class="card-title"> Цена: {{ favorite.price }} ₽</h5>
        <p class="text-truncate">{{ favorite.name }}</p>
        <a href= "{{ favorite.url }}" class="btn btn-primary">Купить</a>
        <button type="button" class="btn btn-outline-info">Удалить ❌</button>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>
{%endblock%}